// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFxeNF0ZZoRIcQfNMw_fowO8_l1kDMio',
    appId: '1:526068087003:web:829b3c47174e42a26b74fe',
    messagingSenderId: '526068087003',
    projectId: 'laundry-app-e5ca2',
    authDomain: 'laundry-app-e5ca2.firebaseapp.com',
    storageBucket: 'laundry-app-e5ca2.firebasestorage.app',
    measurementId: 'G-E88BXRT1VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbmbt31xVpgLLa1SW-Rgwk3tpwGZQIj8',
    appId: '1:526068087003:android:84f97575a3e93f7d6b74fe',
    messagingSenderId: '526068087003',
    projectId: 'laundry-app-e5ca2',
    storageBucket: 'laundry-app-e5ca2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElzi0Je2aBvH-EdJoOQsSy-nzQenLOyM',
    appId: '1:526068087003:ios:926f006694f5f9566b74fe',
    messagingSenderId: '526068087003',
    projectId: 'laundry-app-e5ca2',
    storageBucket: 'laundry-app-e5ca2.firebasestorage.app',
    iosBundleId: 'com.example.laundry',
  );
}
